"""empty message

Revision ID: 19dd7c133135
Revises: 
Create Date: 2022-02-24 19:47:40.977408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19dd7c133135'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('password_hash_key1', sa.String(length=120), nullable=True),
    sa.Column('password_hash_key2', sa.String(length=120), nullable=True),
    sa.Column('password_hash_key3', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
