"""empty message

Revision ID: ac8d1639cda6
Revises: 9d7c44ce5032
Create Date: 2022-02-28 13:42:37.223974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8d1639cda6'
down_revision = '9d7c44ce5032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'status')
    # ### end Alembic commands ###
